apiVersion: apps/v1
kind: Deployment
metadata:
  name: websafety
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websafety
  template:
    metadata:
      labels:
        app: websafety
    spec:
      initContainers:
      - name: config-init
        image: ghcr.io/kvernnc/docker-websafety:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            # On vérifie sur le point de montage réel de l'initContainer
            if [ ! -f /mnt/pvc/etc/license.pem ]; then
              echo "Volume vide ou licence absente. Initialisation..."

              # Copie récursive du contenu par défaut de l'image
              cp -a /opt/websafety/etc/. /mnt/pvc/etc/
              cp -a /opt/websafety/var/. /mnt/pvc/var/

              # Fix des permissions pour être sûr que le container final puisse écrire
              chown -R 100:101 /mnt/pvc/var # UID/GID typiques proxy/squid, à ajuster si besoin
              echo "Initialisation terminée."
            else
              echo "Volume déjà peuplé."
            fi

        volumeMounts:
        - name: websafety-etc-vol
          mountPath: /mnt/pvc/etc
        - name: websafety-var-vol
          mountPath: /mnt/pvc/var

      containers:
      - name: websafety
        image: ghcr.io/kvernnc/docker-websafety:latest
        ports:
        - containerPort: 3128
          name: proxy
        - containerPort: 80
          name: http-admin
        - containerPort: 443
          name: https-admin
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        env:
        - name: TIME_ZONE
          value: "Pacific/Noumea"

        volumeMounts:
        - name: websafety-etc-vol
          mountPath: /opt/websafety/etc
#        - name: websafety-var-vol
#          mountPath: /opt/websafety-ui

      volumes:
      - name: websafety-etc-vol
        persistentVolumeClaim:
          claimName: websafety-etc-pvc
      - name: websafety-var-vol
        persistentVolumeClaim:
          claimName: websafety-var-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: websafety-etc-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 32Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: websafety-var-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 300Mi

---
apiVersion: v1
kind: Service
metadata:
  name: websafety-svc
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: proxy
      port: 3128
    - name: web
      port: 80
    - name: ssl
      port: 443
  selector:
    app: websafety
